[v1_some_model_name]
name = "v1_some_model_name"
seed = 42

[v1_some_model_name.core_params]
input_channels = 1
model_name = 'resnet50_l2_eps_1_0'
layer_name = 'layer3.0'
pretrained = true
bias = false
final_batchnorm = true
final_nonlinearity = true
momentum = 0.1
fine_tune = false

[v1_some_model_name.readout_params]
clone_readout = false

[v1_some_model_name.readout_params.base_readout_params]
in_shape = []
outdims = 32
bias = true
init_mu_range = 0.1
init_sigma = 1
batch_sample = false
align_corners = false
gauss_type = 'full'
feature_reg_weight = 1.0

[v1_some_model_name.non_linearity_params]
offset = -1.0


class GaussianType(Enum):
    ISOTROPIC = 'isotropic'
    UNCORRELATED = 'uncorrelated'
    FULL = 'full'


class FullGaussian2dReadoutParams(BaseModel):
    in_shape: Sequence
    outdims: int
    bias: bool
    init_mu_range: float
    init_sigma: float
    batch_sample: bool
    align_corners: bool
    gauss_type: GaussianType = GaussianType.FULL
    grid_mean_predictor: Optional[Any] = None
    shared_features: Optional[Any] = None
    shared_grid: Optional[Any] = None
    source_grid: Optional[np.ndarray] = None
    mean_activity: Optional[Sequence[int]] = None
    feature_reg_weight: float = 1.0


class EluNonLinearityParams(BaseModel):
    offset: float = -1.0


class ModelParams(BaseModel):
    seed: int
    core_params: TaskDrivenCoreParams
    readout_params: MultiSessionReadoutParams
    non_linearity_params: EluNonLinearityParams